default: &default
  adapter: postgresql
  host: localhost

development:
  adapter: postgresql
  database: pcm_development
  host: localhost

test:
  adapter: postgresql
  database: pcm_test
  host: localhost

staging:
  adapter: postgresql
  encoding: unicode
  database: pcm_staging
  username: ubuntu
  # password: <%= Rails.application.secrets[:database][:password] %>
  pool: 5
  # password: <%= ENV['PCM_DATABASE_PASSWORD'] %>

production:
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  encoding: unicode
  database: pcm_production
  # username: ubuntu
  # password: <%= Rails.application.secrets[:database][:password] %>
  pool: 5
  # password: <%= ENV['PCM_DATABASE_PASSWORD'] %>
